# Generated by Django 4.1.2 on 2023-01-19 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(help_text='Data e hora de entrada', verbose_name='Horário')),
                ('situacao', models.CharField(choices=[('A', 'Agendado'), ('R', 'Realizado'), ('C', 'Cancelado')], default='A', help_text='Situação do atendimento', max_length=15, verbose_name='Situação')),
                ('cliente', models.ForeignKey(help_text='Nome do cliente', on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(help_text='Nome do Funcionário', on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Servico',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
