# Generated by Django 4.1.1 on 2023-01-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_alter_servico_options_servico_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Preço do serviço', max_digits=5, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
