# Generated by Django 4.1.1 on 2023-01-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_servico_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='preco',
        ),
    ]
