# Generated by Django 4.1.2 on 2023-01-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Modelo do Veículo', max_length=10, verbose_name='Modelo')),
                ('placa', models.CharField(help_text='Placa do Veículo', max_length=10, verbose_name='Placa')),
                ('cor', models.CharField(help_text='Cor do Veículo', max_length=10, verbose_name='Cor')),
                ('qtdPneu', models.DecimalField(decimal_places=1, help_text='Quantidade de Pneus', max_digits=1, verbose_name='Quantidade de Pneus')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
