# Generated by Django 4.1.2 on 2023-01-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='qtdPneu',
            field=models.DecimalField(decimal_places=0, help_text='Quantidade de Pneus', max_digits=1, verbose_name='Quantidade de Pneus'),
        ),
    ]
