# Generated by Django 4.1.1 on 2023-01-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_alter_veiculo_qtdpneu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['modelo'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
