# Generated by Django 4.1.2 on 2023-01-19 00:42

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Número do telefone', max_length=15, verbose_name='Telefone')),
                ('endereco', models.CharField(help_text='Endereço Completo', max_length=100, verbose_name='Endereço')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='pessoas', variations={'thumbnail': {'crop': True, 'heigth': 100, 'width': 100}}, verbose_name='Foto')),
                ('cpf', models.CharField(help_text='Cpf', max_length=11, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
